### ISSUE TITLE
Timeout policy hangs forever when calling a remote service

### ISSUE THREAD

**Issue by gjeanmart** [jhalterman/failsafe#209]
Hi,
I'm currently trying to implement a client side timeout when calling a HTTP service but the timeout policy doesn't work and the HTTP request hangs for a very long time before triggering the `TimeoutExceededException`.

**Working example**
Here is a simple example using `Thread.sleep(...)` which works correctly:

```java
    @Test(expected = TimeoutExceededException.class)
    public void timeoutUsingThreadSleep() {
        Timeout<Object> timeoutPolicy = Timeout.of(Duration.ofSeconds(3));
        Failsafe.with(timeoutPolicy)
            .onComplete(e -> log.info("event completed"))
            .onFailure(e -> log.info("event failed", e.getFailure()))
            .run(() -> {
                log.info("[START]");
                Thread.sleep(4000);
                log.info("[END]");
            });
    }
```

**Broken example**
I an trying to replicate a similar example but for a web-service that doesn't respond or perhaps doesn't even exist.

```java
    @Test(expected = TimeoutExceededException.class)
    public void timeoutWithHTTPCall() {
        
        Timeout<Object> timeoutPolicy = Timeout.of(Duration.ofSeconds(3));
        
        Failsafe.with(timeoutPolicy)
            .onComplete(e -> log.info("event completed"))
            .onFailure(e -> log.info("event failed", e.getFailure()))
            .run(() -> {
                log.info("[START]");

                URL target = new URL("https://www.urlthatdonotexist.com");
                HttpURLConnection conn = (HttpURLConnection) target.openConnection();
                conn.setRequestMethod("GET");

                InputStream in = conn.getInputStream();

                log.info("[END]");
            });

    }
```

The latter example doesn't work as expected, it seems the timeout is triggered after a very long time (between one and two minutes) even with a 3 seconds timeout.

```
[2019-10-26 15:55:46,066] [INFO] [FailsafeTest FailsafeTest.java:42] [START]
[2019-10-26 15:57:56,788] [INFO] [FailsafeTest FailsafeTest.java:40] event failed
net.jodah.failsafe.TimeoutExceededException: null
	at net.jodah.failsafe.TimeoutExecutor.lambda$null$0(TimeoutExecutor.java:66)
	at java.util.concurrent.atomic.AtomicReference.getAndUpdate(AtomicReference.java:160)
	at net.jodah.failsafe.TimeoutExecutor.lambda$null$1(TimeoutExecutor.java:66)
	at net.jodah.failsafe.internal.util.DelegatingScheduler.lambda$schedule$0(DelegatingScheduler.java:140)
	at java.util.concurrent.ForkJoinTask$AdaptedCallable.exec(ForkJoinTask.java:1424)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
[2019-10-26 15:57:56,790] [INFO] [FailsafeTest FailsafeTest.java:39] event completed
```

Is there anything I am doing wrong or I missed ?

Thank you.
Greg 

---------------

```
        <dependency>
            <groupId>net.jodah</groupId>
            <artifactId>failsafe</artifactId>
            <version>2.3.1</version>
        </dependency>
```

**Comment by alinposho** [comment]
There could be a number of reasons for the timeout policy not interrupting the operation it is guarding. Among them are (the list is not exhaustive):
1. You are **not** specifying `timeout.withCancel(shouldInterrupt)` as per the documentation. The interrupt relies on the operation being wrapped by the Timeout policy being thread interrupt friendly, i.e. properly responding to [Thread interrupt signals](https://docs.oracle.com/javase/8/docs/api/java/lang/Thread.html#interrupt--). See code sample below.
2. The operation acquires an uninterruptible lock (see code sample below).
3. The operation guarded by the Timeout is not interruptible. There are quite a few HTTP libraries out there that do not respond to thread interrupts,e.g. block waiting for some socket input, and you have to configure a timeout on each operation: connection acquisition, request, etc.

```
public class TimeoutTest {

    private final static Logger log = LoggerFactory.getLogger(TimeoutTest.class);

    private final Duration timeout = Duration.ofMillis(500);
    private final Duration blockDuration = timeout.plusSeconds(1);
    private final Timeout<String> timeoutPolicy = Timeout.<String>of(timeout)
            .withCancel(true);

    @Test
    public void timeout_givenBlockIsLockedInterruptibly_shouldRaiseExceptionAfterTimeoutExceeded() throws ExecutionException, InterruptedException {
        // Given a synchronization primitive that is responsive to thread interrupts
        CountDownLatch latch = new CountDownLatch(1);

        CompletableFuture<Long> future = CompletableFuture.<Long>supplyAsync(() -> {
            long start = System.currentTimeMillis();
            try {
                Failsafe.with(timeoutPolicy)
                        .onComplete(e -> log.info("event completed"))
                        .onFailure(e -> log.info("event failed", e.getFailure()))
                        .get(() -> {
                            log.info("[START]");

                            // The latch responds to thread interrupts, so the TimeoutExceededException will be raised
                            // after the timeout duration has expired.
                            latch.await(blockDuration.getSeconds(), TimeUnit.SECONDS);

                            log.info("[END]");

                            return "100";
                        });
                throw new RuntimeException("We should not reach this point.");
            } catch (TimeoutExceededException e) {
                // Expected Exception
            } finally {
                long end = System.currentTimeMillis();
                return end - start;
            }
        });

        assertThat(future.get(), lessThan(blockDuration.toMillis()));
    }

    @Test
    public void timeout_givenBlockIsLockedUninterruptibly_shouldRaiseExceptionAfterLockIsReleased() throws ExecutionException, InterruptedException {
        // Given a synchronization primitive that ignores thread interruptions
        ReentrantLock lock = new ReentrantLock();
        lock.lock();

        CompletableFuture<Long> future = CompletableFuture.<Long>supplyAsync(() -> {
            long start = System.currentTimeMillis();
            try {
                Failsafe.with(timeoutPolicy)
                        .onComplete(e -> log.info("event completed"))
                        .onFailure(e -> log.info("event failed", e.getFailure()))
                        .get(() -> {
                            log.info("[START]");

                            // When we block for more than the timeout duration since this lock is uninterruptible
                            // and the lock has already been aquired outside the future.
                            lock.lock();

                            log.info("[END]");

                            return "100";
                        });
                throw new RuntimeException("We should not reach this point.");
            } catch (TimeoutExceededException e) {
                // Expected Exception
            } finally {
                long end = System.currentTimeMillis();
                return end - start;
            }
        });

        Thread.sleep(blockDuration.toMillis());
        lock.unlock();

        assertThat(future.get(), greaterThanOrEqualTo(blockDuration.toMillis()));
    }

}


```

**Comment by jhalterman** [comment]
Hopefully @alinposho's response answered this. Feel free to re-open if not.
