### ISSUE TITLE
IllegalStateException: Cannot record result for open circuit

### ISSUE THREAD

**Issue by sunng87** [jhalterman/failsafe#32]
I'm using circuit breaker in a high concurrent environment, and I'm getting this `IllegalStateException`:

```
java.lang.IllegalStateException: Cannot record result for open circuit
  at net.jodah.failsafe.internal.OpenState.recordFailure(OpenState.java:34)
  at net.jodah.failsafe.CircuitBreaker.recordFailure(CircuitBreaker.java:436)
  at net.jodah.failsafe.AbstractExecution.complete(AbstractExecution.java:87)
  at net.jodah.failsafe.SyncFailsafe.call(SyncFailsafe.java:170)
  at net.jodah.failsafe.SyncFailsafe.get(SyncFailsafe.java:42)
```

**Comment by sunng87** [comment]
This issue will make `concurrentExecution` never get chance to decrement, so the state will stuck in HalfOpen and rejects all the execution requests.
